Repository cass-degrees/CASS-Degrees-Code, pull requests merged in 2019-08, with the labels that each got.

#178 Add "Save" and "Save and Exit" Buttons for Editing
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: UAT, feature

#180 Add help documentation for rules and global requirements
  cassdegrees/static/css/style.css
  cassdegrees/static/js/globalrequirements.js
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/globalrequirements.html
  cassdegrees/templates/widgets/rulescripts.html
  cassdegrees/templates/widgets/subplanrules.html
Labels: UAT

#214 Disabled autocomplete on form inputs
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
Labels: Quality Control

#226 Updated SETUP.md to get the bullet points to render correctly
  SETUP.md
Labels: Documentation

#213 Implement student plan creation pipeline
  cassdegrees/static/css/style.css
  cassdegrees/static/js/student_create.js
  cassdegrees/templates/student_create.html
  cassdegrees/templates/student_edit.html
  cassdegrees/templates/student_index.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/student.py
Labels: Creating/Viewing Plans, User Story

#231 Fixed UAT Bug #216 Unable tab number fields
  cassdegrees/static/js/main.js
Labels: UAT, bug

#229 Extra Subplan Rules
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/subplanrules.html
Labels: UAT

#247 Enable the rendering of student plans as PDFs
  cassdegrees/static/css/style.css
  cassdegrees/static/js/student_edit.js
  cassdegrees/templates/pdf_base.html
  cassdegrees/templates/pdf_program.html
  cassdegrees/templates/student_edit.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/ui/templatetags/course_boxes.py
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/pdf.py
  cassdegrees/ui/views/student.py
Labels: Creating/Viewing Plans, User Story

#254 Fixed "Page not found" error when clicking on subplans in Program viewer
  cassdegrees/templates/viewprogram.html
Labels: bug

#244 Added pagination for the list table for Programs, Subplans and Courses
  cassdegrees/static/css/style.css
  cassdegrees/templates/list.html
  cassdegrees/templates/student_edit.html
Labels: feature

#260 Sort courses in Vue List Components
  cassdegrees/static/js/rules.js
Labels: feature

#256 Feature - Add Subplan to Program Plan
  cassdegrees/static/js/student_edit.js
  cassdegrees/templates/student_edit.html
  cassdegrees/templates/widgets/subplan_choice.html
  cassdegrees/ui/templatetags/student_course_boxes.py
  cassdegrees/ui/views/student.py
Labels: Creating/Viewing Plans

#272 View Subplan - At Least, Exactly, No More Than
  cassdegrees/templates/viewsubplan.html
Labels: bug

#253 Fix scaling issues for student edit page on smaller devices
  cassdegrees/static/css/style.css
  cassdegrees/templates/base.html
  cassdegrees/templates/student_edit.html
Labels: bug

#273 Added the ability for users to remove or groups in 'either or ' rules.
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/rules.html
Labels: bug

#274 Add ability to remove first course in a rule if >1 course is defined
  cassdegrees/templates/widgets/rulescripts.html
Labels: feature

#234 Comments Section on Form
  cassdegrees/api/migrations/0001_initial.py
  cassdegrees/api/migrations/0002_auto_20190417_1949.py
  cassdegrees/api/migrations/0003_auto_20190422_1519.py
  cassdegrees/api/migrations/0004_auto_20190501_1318.py
  cassdegrees/api/migrations/0005_auto_20190508_1107.py
  cassdegrees/api/migrations/0006_coursemodel_test.py
  cassdegrees/api/migrations/0007_auto_20190517_0113.py
  cassdegrees/api/migrations/0008_auto_20190517_0131.py
  cassdegrees/api/migrations/0009_programmodel_lastupdated.py
  cassdegrees/api/migrations/0010_auto_20190521_2019.py
  cassdegrees/api/migrations/0011_programmodel_publish.py
  cassdegrees/static/css/style.css
  cassdegrees/static/js/student_edit.js
  cassdegrees/templates/student_edit.html
  weasyprint.pdf
Labels: Creating/Viewing Plans, User Story

#275 Tweak search logic on Student Planner
  cassdegrees/static/css/style.css
  cassdegrees/static/js/fuse.js
  cassdegrees/static/js/fuse.min.js
  cassdegrees/static/js/student_edit.js
  cassdegrees/templates/student_edit.html
  cassdegrees/ui/views/student.py
Labels: bug

#280 Added Min/Max/Exact units from a Course List Rules to Program
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/rulescripts.html
  cassdegrees/templates/widgets/subplanrules.html
Labels: Template Creation, bug
