Repository cass-degrees/CASS-Degrees-Code, pull requests merged in 2019-04, with the labels that each got.

#4 Add, edit and remove records from a table in a postgresql database
  cassdegrees/api/admin.py
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/api/urls.py
  cassdegrees/api/views.py
  cassdegrees/cassdegrees/urls.py
Labels: feature

#46 Create and register a folder that contains the CSS, img and js files
  cassdegrees/cassdegrees/settings.py
  cassdegrees/static/css/style.css
  cassdegrees/static/img/please delete after first img.txt
  cassdegrees/static/js/sample.js
  cassdegrees/templates/index.html
Labels: feature

#47 Implement base template conformant to ANU styling
  cassdegrees/static/css/style.css
  cassdegrees/templates/base.html
  cassdegrees/templates/index.html
Labels: Intermediate Task

#49 Create Empty Data Tables
  cassdegrees/api/admin.py
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/api/urls.py
  cassdegrees/api/views.py
Labels: Intermediate Task

#48 Add, edit and delete records from the sample model using a custom-made very basic UI Form
  cassdegrees/templates/sampleform.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views.py
  requirements.txt
Labels: Editing & Removal, feature

#51 Fixed incorrect url in sampleform() and also added some comments to it.
  cassdegrees/ui/views.py
Labels: bug

#53 View template or subplan list
  cassdegrees/templates/list.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views.py
Labels: Accessing Existing Plans, User Story

#54 Implemented flake8 and desired settings in setup.cfg
  .pep8speaks.yml
  cassdegrees/api/serializers.py
  cassdegrees/api/urls.py
  cassdegrees/setup.cfg
  requirements.txt
Labels: Quality Control

#57 Data list page improvements
  cassdegrees/templates/list.html
  cassdegrees/ui/views.py
Labels: feature

#62 Added search capabilities for degrees, subplans, and courses
  cassdegrees/static/css/style.css
  cassdegrees/templates/list.html
  cassdegrees/ui/views.py
Labels: Accessing Existing Plans, User Story

#66 Bulk Data Upload
  cassdegrees/templates/bulkupload.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views.py
Labels: Course/Subplan Addition, User Story, feature

#67 Add support for adding/removing global requirements from a program
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/static/css/style.css
  cassdegrees/static/js/pristine.js
  cassdegrees/static/js/programmanagement.js
  cassdegrees/templates/createprogram.html
  cassdegrees/ui/views.py
Labels: Template Creation, User Story

#61 Base Code for Course Edit and Delete
  cassdegrees/templates/list.html
  cassdegrees/templates/managecourses.html
  cassdegrees/ui/views.py
Labels: Editing & Removal, feature

#68 Added UI improvements to Add Course form
  cassdegrees/templates/managecourses.html
Labels: feature

#70 Basic program and subplan removal + bug fixes
  cassdegrees/templates/list.html
  cassdegrees/templates/manageprograms.html
  cassdegrees/templates/managesubplans.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views.py
Labels: Editing & Removal

#75 Search api
  cassdegrees/api/urls.py
  cassdegrees/api/views.py
  cassdegrees/templates/list.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views.py
Labels: feature

#77 Fix a bug in `/list` table
  cassdegrees/ui/views.py
Labels: bug

#74 Finalisation of Course Deletion
  cassdegrees/templates/list.html
  cassdegrees/templates/managecourses.html
  cassdegrees/ui/views.py
Labels: Editing & Removal, User Story, feature

#79 Cleanup view management, use ModelForms for creating programs and subplans
  cassdegrees/__init__.py
  cassdegrees/api/models.py
  cassdegrees/static/css/style.css
  cassdegrees/static/js/programmanagement.js
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/list.html
  cassdegrees/templates/managecourses.html
  cassdegrees/templates/manageprograms.html
  cassdegrees/templates/managesubplans.html
  cassdegrees/templates/widgets/globalrequirements.html
  cassdegrees/ui/admin.py
  cassdegrees/ui/forms.py
  cassdegrees/ui/models.py
  cassdegrees/ui/tests.py
  cassdegrees/ui/urls.py
  cassdegrees/ui/views.py
  cassdegrees/ui/views/__init__.py
  cassdegrees/ui/views/bulk_data_upload.py
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/index.py
  cassdegrees/ui/views/listings.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/sampleform.py
  cassdegrees/ui/views/subplans.py
Labels: Quality Control

#80 Complete management tools for programs, subplans and courses
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/deletecourses.html
  cassdegrees/templates/deleteprograms.html
  cassdegrees/templates/deletesubplans.html
  cassdegrees/templates/list.html
  cassdegrees/templates/managecourses.html
  cassdegrees/templates/manageprograms.html
  cassdegrees/templates/managesubplans.html
  cassdegrees/ui/forms.py
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/listings.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: Editing & Removal, Quality Control

#76 Link Subplans to Course Codes
  cassdegrees/api/admin.py
  cassdegrees/api/degreeRules.py
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/api/urls.py
  cassdegrees/api/views.py
Labels: Quality Control

#86 Add a breadcrumb trail to pages
  cassdegrees/templates/base.html
  cassdegrees/templates/bulkupload.html
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/deletecourses.html
  cassdegrees/templates/deleteprograms.html
  cassdegrees/templates/deletesubplans.html
  cassdegrees/templates/index.html
  cassdegrees/templates/list.html
  cassdegrees/templates/managecourses.html
  cassdegrees/templates/sampleform.html
  cassdegrees/ui/templatetags/__init__.py
  cassdegrees/ui/templatetags/breadcrumbs.py
Labels: feature

#90 Fix crashing of develop branch caused by the import of a non existing model
  cassdegrees/ui/views/courses.py
Labels: bug

#87 Template Duplication
  cassdegrees/templates/list.html
  cassdegrees/ui/views/programs.py
Labels: Template Creation, User Story
