Repository cass-degrees/CASS-Degrees-Code, pull requests merged in 2019-09, with the labels that each got.

#300 Remove First Item from Subplan Rule in Program Edit and Course Rule in Subplan Edit
  cassdegrees/templates/widgets/rulescripts.html
  cassdegrees/templates/widgets/subplanrules.html
Labels: feature

#301 General Elective Rule
  cassdegrees/static/js/rules.js
  cassdegrees/templates/viewcourse.html
  cassdegrees/templates/viewprogram.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/templates/widgets/rulescripts.html
  cassdegrees/templates/widgets/student_rules.html
Labels: Creating/Viewing Plans, feature

#298 Feature integrated subplan
  cassdegrees/static/js/student_edit.js
  cassdegrees/templates/student_edit.html
  cassdegrees/templates/widgets/student_rules.html
  cassdegrees/templates/widgets/subplan_choice.html
  cassdegrees/ui/templatetags/student_course_boxes.py
  cassdegrees/ui/views/student.py
Labels: Creating/Viewing Plans, feature

#303 Fixed breadcrumbs on create list page
  cassdegrees/templates/createlist.html
Labels: bug

#307 Restyled Index Buttons to Wrap and Center Align When Resized.
  cassdegrees/static/css/style.css
  cassdegrees/templates/index.html
  cassdegrees/ui/views/index.py
Labels: bug

#291 Improved Success Messages
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: feature

#292 Min/Exact/Max Units from Course List in View Program
  cassdegrees/templates/viewprogram.html
Labels: feature

#305 Code cleanup: Refactor components into modules
  cassdegrees/static/js/staff/globalrequirements.js
  cassdegrees/static/js/staff/rules.js
  cassdegrees/static/js/student/create.js
  cassdegrees/static/js/student/edit.js
  cassdegrees/static/js/vendor/fuse.js
  cassdegrees/static/js/vendor/fuse.min.js
  cassdegrees/static/js/vendor/interact.js
  cassdegrees/static/js/vendor/interact.min.js
  cassdegrees/static/js/vendor/list.js
  cassdegrees/static/js/vendor/vue-multiselect.js
  cassdegrees/static/js/vendor/vue-resource.js
  cassdegrees/static/js/vendor/vue.js
  cassdegrees/templates/sampleform.html
  cassdegrees/templates/staff/bulkupload.html
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/staff/delete/deletecourses.html
  cassdegrees/templates/staff/delete/deleteprograms.html
  cassdegrees/templates/staff/delete/deletesubplans.html
  cassdegrees/templates/staff/index.html
  cassdegrees/templates/staff/list.html
  cassdegrees/templates/staff/view/viewcourse.html
  cassdegrees/templates/staff/view/viewprogram.html
  cassdegrees/templates/staff/view/viewsubplan.html
  cassdegrees/templates/student/create.html
  cassdegrees/templates/student/edit.html
  cassdegrees/templates/student/index.html
  cassdegrees/templates/widgets/staff/courselistingwidget.html
  cassdegrees/templates/widgets/staff/courserequisites.html
  cassdegrees/templates/widgets/staff/globalrequirements.html
  cassdegrees/templates/widgets/staff/rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
  cassdegrees/templates/widgets/student/rules.html
  cassdegrees/templates/widgets/student/subplan_choice.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/pdf.py
  cassdegrees/ui/views/sampleform.py
  cassdegrees/ui/views/staff/__init__.py
  cassdegrees/ui/views/staff/bulk_data_upload.py
  cassdegrees/ui/views/staff/courses.py
  cassdegrees/ui/views/staff/index.py
  cassdegrees/ui/views/staff/listings.py
  cassdegrees/ui/views/staff/lists.py
  cassdegrees/ui/views/staff/programs.py
  cassdegrees/ui/views/staff/subplans.py
  cassdegrees/ui/views/staff/view.py
  cassdegrees/ui/views/student.py
Labels: Quality Control

#309 Streamline course model
  cassdegrees/api/migrations/__init__.py
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/templates/staff/delete/deletecourses.html
  cassdegrees/templates/staff/view/viewcourse.html
  cassdegrees/ui/forms.py
  cassdegrees/ui/views/staff/courses.py
  cassdegrees/ui/views/staff/listings.py
Labels: Course/Subplan Addition, Editing & Removal

#327 Fixed the .gitignore issue and added __init__.py
  .gitignore
  cassdegrees/api/migrations/__init__.py
Labels: Difficulty: EASY, bug

#328 Fixed link for subplans within the 'either or' rule.
  cassdegrees/templates/staff/view/viewprogram.html
Labels: Difficulty: EASY, bug

#329 Course creation on forms without changing page
  cassdegrees/static/css/style.css
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/widgets/staff/coursecreatepopup.html
  cassdegrees/templates/widgets/staff/courselistingwidget.html
  cassdegrees/ui/views/staff/courses.py
  cassdegrees/ui/views/staff/lists.py
  cassdegrees/ui/views/staff/programs.py
  cassdegrees/ui/views/staff/subplans.py
Labels: feature

#331 Improve readability of form elements on screen
  cassdegrees/static/css/anu-style-override.css
  cassdegrees/static/css/style.css
  cassdegrees/templates/base.html
  cassdegrees/ui/forms.py
Labels: Quality Control

#333 Set the default value of 'currentlyActive' to be true.
  cassdegrees/api/models.py
Labels: Course Model Update, Difficulty: EASY

#330 Subject Area Global Requirements
  cassdegrees/static/js/staff/globalrequirements.js
  cassdegrees/templates/pdf_program.html
  cassdegrees/templates/staff/view/viewprogram.html
  cassdegrees/templates/widgets/staff/globalrequirements.html
  cassdegrees/ui/views/staff/view.py
Labels: feature

#314 table border only shows if there is data available.
  cassdegrees/templates/staff/list.html
Labels: Quality Control, UAT

#339 Clarified Error Messages
  cassdegrees/templates/widgets/staff/globalrequirements.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
  cassdegrees/ui/forms.py
Labels: Difficulty: EASY, UAT

#343 Empty Dropdowns When No Course/Subplan/Program in Database
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
Labels: Difficulty: EASY, UAT, bug

#354 Feature Delete Button in Edit
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/staff/list.html
Labels: Difficulty: EASY, UAT, feature

#353 Fixed cancel button redirects
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
Labels: Quality Control, UAT, bug

#363 OR Rule Unit Notification
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
Labels: feature

#351 Implement confirmation box for saving non-public programs/subplans
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
Labels: UAT, feature

#352 Verify that plan links exist when setting up a popup
  cassdegrees/static/js/student/edit.js
Labels: bug

#340 Feature Duplicate Rules
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/courserequisites.html
  cassdegrees/templates/widgets/staff/rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
Labels: Difficulty: MEDIUM, Editing & Removal, Template Creation, UAT

#364 Uat list integration
  cassdegrees/api/views.py
  cassdegrees/static/css/style.css
  cassdegrees/static/css/vue-multiselect.css
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/courselistingwidget.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
  cassdegrees/ui/views/staff/lists.py
Labels: Difficulty: HARD, UAT

#362 Implement several security checks for API endpoints
  cassdegrees/api/views.py
Labels: Difficulty: MEDIUM, Quality Control, bug

#337 Added Visual Cues to Rule Creation
  cassdegrees/static/css/style.css
  cassdegrees/static/js/staff/globalrequirements.js
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/courserequisites.html
  cassdegrees/templates/widgets/staff/rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
Labels: Quality Control, UAT, feature

#369 Uat delete lists
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/templates/staff/delete/deletelists.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/staff/lists.py
Labels: Editing & Removal, UAT

#381 Implement view page for lists and correct course_creation_form error …
  cassdegrees/templates/staff/view/viewlist.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/staff/lists.py
  cassdegrees/ui/views/staff/view.py
Labels: Difficulty: MEDIUM, UAT, bug

#378 Fix "Create Subplan" Button From Program Edit
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/widgets/staff/coursecreatepopup.html
Labels: bug

#366 Unique Course Rule Identifiers
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/staff/view/viewcourse.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/ui/templatetags/course_boxes.py
  cassdegrees/ui/templatetags/student_course_boxes.py
  cassdegrees/ui/views/staff/view.py
Labels: bug

#376 Feature Course Report
  cassdegrees/templates/staff/list.html
  cassdegrees/templates/staff/report/coursereport.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/staff/report.py
Labels: UAT, feature

#375 Checking filetype of uploaded file for bulk uploading
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: Quality Control, bug

#384 Add global requirements rule to subplans
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/staff/view/viewsubplan.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/ui/forms.py
  cassdegrees/ui/views/staff/view.py
Labels: bug, feature

#386 Changed display text and added a help field for advice.
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/rulescripts.html
Labels: Difficulty: EASY, UAT

#382 Add verification for plan and subplan vue rules
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/widgets/staff/rules.html
Labels: feature

#387 Fix hovering checkboxes by pushing modals above the rest of the page
  cassdegrees/static/css/style.css
Labels: Difficulty: EASY, bug

#403 Changed 'At least' to 'A Minimum of' and 'No more than' to 'A Maximum…
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/staff/view/viewprogram.html
  cassdegrees/templates/staff/view/viewsubplan.html
Labels: Difficulty: EASY, Wishlist

#399 Made delete messages consistent
  cassdegrees/templates/staff/delete/deletecourses.html
  cassdegrees/templates/staff/delete/deletelists.html
  cassdegrees/templates/staff/delete/deleteprograms.html
  cassdegrees/templates/staff/delete/deletesubplans.html
Labels: Quality Control

#390 Added feature to generate excel files for the courses report.
  cassdegrees/templates/staff/list.html
  cassdegrees/templates/staff/report/coursereport.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/staff/report.py
  requirements.txt
Labels: UAT, feature

#398 Autofill Year for Subplan Created from Program
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/ui/views/staff/programs.py
  cassdegrees/ui/views/staff/subplans.py
Labels: feature

#392 Uat searchable subplan ui
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
Labels: Difficulty: HARD, UAT

#388 Updated messages to make publish clearer to the user
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
Labels: Quality Control, UAT

#389 Minimum Maximum Course Rule Option
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/staff/view/viewprogram.html
  cassdegrees/templates/staff/view/viewsubplan.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplanrules.html
  cassdegrees/templates/widgets/student/rules.html
Labels: feature

#412 added subplan type on viewprogram (subplan rule, OR rule)
  cassdegrees/templates/staff/view/viewprogram.html
Labels: Difficulty: EASY, Wishlist

#391 Fix custom text rule checkbox rendering
  cassdegrees/static/css/style.css
  cassdegrees/templates/widgets/staff/globalrequirements.html
  cassdegrees/templates/widgets/staff/rulescripts.html
Labels: bug

#394 Refactor rules
  cassdegrees/static/js/staff/globalrequirements.js
  cassdegrees/static/js/staff/rules.js
  cassdegrees/static/js/staff/rules/course_elective.js
  cassdegrees/static/js/staff/rules/course_requisite.js
  cassdegrees/static/js/staff/rules/course_selection.js
  cassdegrees/static/js/staff/rules/custom_text.js
  cassdegrees/static/js/staff/rules/custom_text_requirement.js
  cassdegrees/static/js/staff/rules/either_or.js
  cassdegrees/static/js/staff/rules/enrolled_program.js
  cassdegrees/static/js/staff/rules/incompatibility.js
  cassdegrees/static/js/staff/rules/rule.js
  cassdegrees/static/js/staff/rules/rule_container.js
  cassdegrees/static/js/staff/rules/subplan.js
  cassdegrees/templates/base.html
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/widgets/rules/blank.html
  cassdegrees/templates/widgets/rules/course_elective.html
  cassdegrees/templates/widgets/rules/course_requisite.html
  cassdegrees/templates/widgets/rules/course_selection.html
  cassdegrees/templates/widgets/rules/custom_text.html
  cassdegrees/templates/widgets/rules/custom_text_requirement.html
  cassdegrees/templates/widgets/rules/either_or.html
  cassdegrees/templates/widgets/rules/enrolled_program.html
  cassdegrees/templates/widgets/rules/incompatibility.html
  cassdegrees/templates/widgets/rules/resources.html
  cassdegrees/templates/widgets/rules/rule.html
  cassdegrees/templates/widgets/rules/rule_container.html
  cassdegrees/templates/widgets/rules/subplan.html
  cassdegrees/templates/widgets/staff/course_rules.html
  cassdegrees/templates/widgets/staff/courserequisites.html
  cassdegrees/templates/widgets/staff/global_requirements.html
  cassdegrees/templates/widgets/staff/program_rules.html
  cassdegrees/templates/widgets/staff/rulescripts.html
  cassdegrees/templates/widgets/staff/subplan_rules.html
  cassdegrees/templates/widgets/staff/subplanrules.html
Labels: Difficulty: HARD, Quality Control

#419 Unique Course Codes
  cassdegrees/api/models.py
  cassdegrees/ui/forms.py
Labels: Difficulty: EASY, bug
