Repository cass-degrees/CASS-Degrees-Code, pull requests merged in 2019-05, with the labels that each got.

#93 Subplan Saving
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/ui/forms.py
Labels: Course/Subplan Addition, User Story

#82 Implement rule definitions w/ ModelForm system
  cassdegrees/api/models.py
  cassdegrees/static/css/style.css
  cassdegrees/static/js/globalrequirements.js
  cassdegrees/static/js/pristine.js
  cassdegrees/static/js/programmanagement.js
  cassdegrees/static/js/rules.js
  cassdegrees/static/js/vue.js
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/widgets/globalrequirements.html
  cassdegrees/templates/widgets/rules.html
  cassdegrees/ui/forms.py
Labels: Template Creation, User Story

#94 Feature view plans and subplans
  cassdegrees/templates/list.html
  cassdegrees/templates/viewcourse.html
  cassdegrees/templates/viewprogram.html
  cassdegrees/templates/viewsubplan.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/view_.py
Labels: User Story, feature

#97 Subplan deletion now checks if the subplan is used by a degree
  cassdegrees/templates/list.html
  cassdegrees/ui/views/listings.py
  cassdegrees/ui/views/subplans.py
Labels: Editing & Removal, User Story, feature

#98 Created Readme file for the project codebase
  README.md
  SETUP.md
Labels: Documentation

#99 Create Subplan During Template Creation (PR)
  cassdegrees/templates/createprogram.html
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: Template Creation, User Story

#107 Make search API results distinct and other minor improvements
  cassdegrees/api/views.py
Labels: feature

#103 Bug Course Deletion Check v3000
  cassdegrees/templates/deletecourses.html
  cassdegrees/ui/views/courses.py
Labels: Editing & Removal, User Story, bug, feature

#102 Feature subplan compulsory elective courses v2
  cassdegrees/static/js/rules.js
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/widgets/rules.html
  cassdegrees/templates/widgets/subplanrules.html
Labels: Course/Subplan Addition, User Story

#108 Course Duplication
  cassdegrees/templates/list.html
  cassdegrees/ui/views/courses.py
Labels: Course/Subplan Addition

#111 Created Subject-Area Specific Units Rule in Program Template Creation
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/rules.html
Labels: Template Creation, User Story

#112 Created Year-Specific Units Rule in Program Template Creation
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/rules.html
Labels: Template Creation, User Story

#137 Deleted redundant initial commit file
  initial_commit.txt
Labels: Quality Control

#134 "New __" Buttons Improvements
  cassdegrees/templates/list.html
Labels: feature

#133 Changed 'Edit' buttons to 'Save' buttons
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createsubplan.html
Labels: Editing & Removal, feature

#135 Implemented Select All Feature for Program/Subplan/Courses
  cassdegrees/templates/list.html
Labels: Editing & Removal, Wishlist, feature

#138 Fixed Bug in Duplicate Error Message
  cassdegrees/ui/forms.py
Labels: Editing & Removal, Quality Control, UAT, bug

#140 fixed bug where you couldnt delete any courses
  cassdegrees/templates/list.html
Labels: Editing & Removal, bug

#145 Fixed bug in subplan deletion (Issue #141)
  cassdegrees/ui/views/subplans.py
Labels: bug

#143 Disable submitting on enter key
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
Labels: UAT, feature

#147 Clean up listings page with filtering and neatened labels
  cassdegrees/templates/list.html
  cassdegrees/ui/views/listings.py
Labels: Accessing Existing Plans, feature

#146 Fixed issue with number inputs taking non-numbers (Bug #132)
  cassdegrees/static/js/main.js
  cassdegrees/static/js/sample.js
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/widgets/globalrequirements.html
  cassdegrees/templates/widgets/rules.html
  cassdegrees/templates/widgets/subplanrules.html
  cassdegrees/ui/forms.py
Labels: Quality Control, bug

#148 Updated forms to have better input validation
  cassdegrees/ui/forms.py
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/subplans.py
Labels: Quality Control, UAT, Wishlist, bug

#151 Fixed bug #150 - Deleting when nothing is selected
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: Quality Control, bug

#144 Change icons on homepage as per UAT
  cassdegrees/static/css/style.css
  cassdegrees/static/img/create_course_img.png
  cassdegrees/static/img/manage_courses_img.png
  cassdegrees/templates/index.html
  cassdegrees/ui/views/index.py
Labels: UAT, feature

#153 'Last Updated' Field to Course/Subplan/Program Models
  cassdegrees/api/models.py
  cassdegrees/ui/forms.py
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/listings.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: UAT, feature

#142 Implement PDF rendering of programs
  cassdegrees/static/js/rules.js
  cassdegrees/templates/list.html
  cassdegrees/templates/managecourses.html
  cassdegrees/templates/pdf_base.html
  cassdegrees/templates/pdf_program.html
  cassdegrees/templates/viewprogram.html
  cassdegrees/templates/widgets/rules.html
  cassdegrees/ui/templatetags/course_boxes.py
  cassdegrees/ui/templatetags/math.py
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/pdf.py
  cassdegrees/ui/views/view_.py
  requirements.txt
Labels: Template Creation, User Story

#154 Finalised program Either Or rules
  cassdegrees/static/js/rules.js
  cassdegrees/templates/widgets/rules.html
Labels: feature

#155 Feature authentication
  cassdegrees/api/Validators.py
  cassdegrees/cassdegrees/settings.py
  cassdegrees/cassdegrees/urls.py
  cassdegrees/static/css/style.css
  cassdegrees/templates/base.html
  cassdegrees/templates/registration/logged_out.html
  cassdegrees/templates/registration/login.html
  cassdegrees/templates/registration/password_change_done.html
  cassdegrees/templates/registration/password_change_form.html
  cassdegrees/ui/views/bulk_data_upload.py
  cassdegrees/ui/views/courses.py
  cassdegrees/ui/views/index.py
  cassdegrees/ui/views/listings.py
  cassdegrees/ui/views/programs.py
  cassdegrees/ui/views/subplans.py
Labels: feature

#157 Increase size of home button in breadcrumbs
  cassdegrees/templates/base.html
Labels: Quality Control, UAT

#158 Vectorise icons, add icons to dropdown menu
  cassdegrees/static/css/fontawesome.css
  cassdegrees/static/css/fontawesome.min.css
  cassdegrees/static/css/style.css
  cassdegrees/static/img/create_course_img.png
  cassdegrees/static/img/create_plan_img.png
  cassdegrees/static/img/create_subplan_img.png
  cassdegrees/static/img/open_existing_img.png
  cassdegrees/static/webfonts/fa-brands-400.eot
  cassdegrees/static/webfonts/fa-brands-400.svg
  cassdegrees/static/webfonts/fa-brands-400.ttf
  cassdegrees/static/webfonts/fa-brands-400.woff
  cassdegrees/static/webfonts/fa-brands-400.woff2
  cassdegrees/static/webfonts/fa-regular-400.eot
  cassdegrees/static/webfonts/fa-regular-400.svg
  cassdegrees/static/webfonts/fa-regular-400.ttf
  cassdegrees/static/webfonts/fa-regular-400.woff
  cassdegrees/static/webfonts/fa-regular-400.woff2
  cassdegrees/static/webfonts/fa-solid-900.eot
  cassdegrees/static/webfonts/fa-solid-900.svg
  cassdegrees/static/webfonts/fa-solid-900.ttf
  cassdegrees/static/webfonts/fa-solid-900.woff
  cassdegrees/static/webfonts/fa-solid-900.woff2
  cassdegrees/templates/base.html
  cassdegrees/templates/index.html
  cassdegrees/templates/widgets/globalrequirements.html
  cassdegrees/templates/widgets/rules.html
  cassdegrees/templates/widgets/subplanrules.html
  cassdegrees/ui/views/index.py
Labels: Quality Control

#159 Added Cancel Buttons to Create/Edit pages
  cassdegrees/static/js/main.js
  cassdegrees/templates/createcourse.html
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/createsubplan.html
  cassdegrees/templates/deletecourses.html
  cassdegrees/templates/deleteprograms.html
  cassdegrees/templates/deletesubplans.html
Labels: feature

#163 Prevent Course Code Change if Program/Subplan Requires It
  cassdegrees/templates/createcourse.html
  cassdegrees/ui/forms.py
  cassdegrees/ui/views/courses.py
Labels: Editing & Removal, feature

#160 Code Fixes and Improvements
  cassdegrees/api/models.py
  cassdegrees/api/serializers.py
  cassdegrees/static/js/rules.js
  cassdegrees/templates/createprogram.html
  cassdegrees/ui/forms.py
Labels: bug, feature

#165 Subplan Restriction + Error Messages
  cassdegrees/templates/widgets/rulescripts.html
Labels: feature

#169 Add all rules to `view` pages
  cassdegrees/static/js/rules.js
  cassdegrees/templates/viewcourse.html
  cassdegrees/templates/viewprogram.html
  cassdegrees/templates/viewsubplan.html
  cassdegrees/ui/views/view_.py
Labels: feature

#168 Added strict checks to ensure blank rules cannot be submitted
  cassdegrees/static/js/rules.js
  cassdegrees/templates/createprogram.html
  cassdegrees/templates/widgets/rulescripts.html
Labels: Quality Control, bug
