Repository cass-degrees/CASS-Degrees-Code, pull requests merged in 2019-10, with the labels that each got.

#420 Fix caching issues
  cassdegrees/templates/base.html
  cassdegrees/templates/pdf_base.html
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/staff/delete/deletecourses.html
  cassdegrees/templates/staff/delete/deletelists.html
  cassdegrees/templates/staff/delete/deleteprograms.html
  cassdegrees/templates/staff/delete/deletesubplans.html
  cassdegrees/templates/student/create.html
  cassdegrees/templates/student/edit.html
  cassdegrees/templates/widgets/rules/blank.html
  cassdegrees/templates/widgets/rules/course_elective.html
  cassdegrees/templates/widgets/rules/course_requisite.html
  cassdegrees/templates/widgets/rules/course_selection.html
  cassdegrees/templates/widgets/rules/custom_text.html
  cassdegrees/templates/widgets/rules/custom_text_requirement.html
  cassdegrees/templates/widgets/rules/either_or.html
  cassdegrees/templates/widgets/rules/enrolled_program.html
  cassdegrees/templates/widgets/rules/incompatibility.html
  cassdegrees/templates/widgets/rules/rule.html
  cassdegrees/templates/widgets/rules/rule_container.html
  cassdegrees/templates/widgets/rules/subplan.html
  cassdegrees/templates/widgets/staff/course_rules.html
  cassdegrees/templates/widgets/staff/coursecreatepopup.html
  cassdegrees/templates/widgets/staff/courselistingwidget.html
  cassdegrees/templates/widgets/staff/global_requirements.html
  cassdegrees/templates/widgets/staff/program_rules.html
  cassdegrees/templates/widgets/staff/subplan_rules.html
  cassdegrees/ui/templatetags/cache_control.py
Labels: bug, feature

#418 Rule and Or Group reordering Take 2
  cassdegrees/static/js/staff/rules/either_or.js
  cassdegrees/static/js/staff/rules/rule_container.js
  cassdegrees/templates/widgets/rules/either_or.html
  cassdegrees/templates/widgets/rules/rule.html
  cassdegrees/templates/widgets/rules/rule_container.html
Labels: UAT, feature

#423 Fix course list issues and OR unit count verification
  cassdegrees/static/js/staff/rules/course_selection.js
  cassdegrees/templates/widgets/rules/course_selection.html
Labels: bug

#430 Custom no courses error and changes to rendering order.
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/ui/forms.py
Labels: Difficulty: EASY, UAT

#431 Implement Several Small Improvements
  cassdegrees/static/js/staff/rules/course_elective.js
  cassdegrees/static/js/staff/rules/course_selection.js
  cassdegrees/static/js/staff/rules/custom_text.js
  cassdegrees/templates/widgets/rules/course_elective.html
  cassdegrees/templates/widgets/rules/course_selection.html
  cassdegrees/templates/widgets/rules/custom_text.html
Labels: Difficulty: EASY, Quality Control, bug

#426 Update Bulk Uploader to support excel file format generated by Course Report
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: Difficulty: MEDIUM, feature

#428 Added Placeholder Text into Year/Unit Fields
  cassdegrees/ui/forms.py
Labels: UAT

#429 Added the ability to clear a recent search.
  cassdegrees/static/css/style.css
  cassdegrees/templates/staff/list.html
Labels: feature

#439 Course List Styling Review - Take II
  cassdegrees/static/css/style.css
  cassdegrees/static/js/staff/rules/course_selection.js
  cassdegrees/static/js/staff/rules/subplan.js
  cassdegrees/templates/widgets/rules/course_selection.html
  cassdegrees/templates/widgets/rules/subplan.html
  cassdegrees/templates/widgets/staff/courselistingwidget.html
  cassdegrees/ui/templatetags/cache_control.py
Labels: feature

#435 Fix minor uat issues
  cassdegrees/static/js/staff/rules.js
  cassdegrees/static/js/staff/rules/course_selection.js
  cassdegrees/static/js/staff/rules/either_or.js
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
  cassdegrees/templates/widgets/rules/course_selection.html
  cassdegrees/templates/widgets/rules/subplan.html
Labels: Difficulty: EASY, Quality Control, UAT, bug

#447 Simple year change bugfix
  cassdegrees/static/js/staff/rules/subplan.js
Labels: bug

#434 Select All (In Current Page/All Entries) in Course/Subplan/Program List
  cassdegrees/static/css/style.css
  cassdegrees/templates/staff/list.html
Labels: feature

#445 View/Download Bulk Upload Failures
  cassdegrees/static/css/style.css
  cassdegrees/templates/staff/bulkupload.html
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: UAT

#424 added either_or and custom text rules to subplan
  cassdegrees/static/js/staff/rules.js
  cassdegrees/static/js/staff/rules/custom_text.js
  cassdegrees/static/js/staff/rules/either_or.js
  cassdegrees/static/js/staff/rules/rule_container.js
  cassdegrees/templates/widgets/rules/custom_text.html
  cassdegrees/templates/widgets/rules/either_or.html
  cassdegrees/templates/widgets/staff/subplan_rules.html
Labels: Difficulty: EASY, feature

#448 Fixed the resize styling on search buttons.
  cassdegrees/static/css/style.css
  cassdegrees/templates/staff/list.html
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: bug

#425 Modify PDF styling to improve various aspects of display
  cassdegrees/templates/pdf_base.html
  cassdegrees/templates/pdf_program.html
  cassdegrees/templates/student/edit.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/templates/widgets/student/rules.html
  cassdegrees/templates/widgets/student/subplan_choice.html
  cassdegrees/ui/templatetags/course_boxes.py
  cassdegrees/ui/templatetags/student_course_boxes.py
Labels: Difficulty: HARD, Quality Control

#455 Fixed bug where other_offering was always set as 'True'.
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: Difficulty: EASY, bug

#453 Delete feature in Edit List
  cassdegrees/templates/staff/creation/createlist.html
Labels: Difficulty: EASY, feature

#460 Fix outputting of JSON on student page for specific rules
  cassdegrees/templates/widgets/student/rules.html
Labels: bug

#462 Implement add all of the currently filtered subplan types, and correc…
  cassdegrees/static/js/staff/rules/subplan.js
  cassdegrees/templates/widgets/rules/subplan.html
Labels: Difficulty: MEDIUM, UAT

#461 Draggable rules
  cassdegrees/static/css/style.css
  cassdegrees/static/js/staff/rules.js
  cassdegrees/static/js/staff/rules/either_or.js
  cassdegrees/static/js/staff/rules/rule.js
  cassdegrees/static/js/staff/rules/rule_container.js
  cassdegrees/templates/widgets/rules/either_or.html
  cassdegrees/templates/widgets/rules/rule.html
  cassdegrees/templates/widgets/rules/rule_container.html
Labels: UAT, feature

#463 Remove Flexible Vertical Option from Program Types
  cassdegrees/api/models.py
Labels: UAT

#464 Fixed Errors with Viewing Programs and Subplans
  cassdegrees/templates/staff/view/viewprogram.html
  cassdegrees/templates/staff/view/viewsubplan.html
  cassdegrees/ui/views/staff/view.py
Labels: bug

#459 Implement check to verify that unsaved changes are acknowledged
  cassdegrees/static/js/main.js
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
Labels: Difficulty: MEDIUM, UAT, Wishlist

#465 Tooltips on Add Rule Popup Dialog
  cassdegrees/static/js/staff/rules.js
  cassdegrees/static/js/staff/rules/either_or.js
  cassdegrees/static/js/staff/rules/rule_container.js
  cassdegrees/templates/widgets/rules/either_or.html
  cassdegrees/templates/widgets/rules/rule_container.html
Labels: feature

#470 Fix Course Report from generating malformed excel files
  cassdegrees/ui/views/staff/bulk_data_upload.py
  cassdegrees/ui/views/staff/report.py
  requirements.txt
Labels: bug

#473 Bugfix duplicate error on course edit
  cassdegrees/ui/forms.py
Labels: Difficulty: EASY, bug

#471 Publish Button Prompt and Workflow
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/templates/staff/creation/createprogram.html
  cassdegrees/templates/staff/creation/createsubplan.html
Labels: UAT

#480 Add course list rule to `View` OR rules
  cassdegrees/static/css/style.css
  cassdegrees/static/js/staff/rules.js
  cassdegrees/templates/staff/view/viewprogram.html
  cassdegrees/templates/widgets/rules/either_or.html
Labels: bug

#458 Student portal page for end of project
  cassdegrees/static/js/student/list.js
  cassdegrees/static/js/vendor/fuse.js
  cassdegrees/static/js/vendor/fuse.min.js
  cassdegrees/templates/student/create.html
  cassdegrees/templates/student/index.html
  cassdegrees/templates/student/prototype.html
  cassdegrees/ui/urls.py
  cassdegrees/ui/views/pdf.py
  cassdegrees/ui/views/staff/index.py
  cassdegrees/ui/views/student.py
Labels: Creating/Viewing Plans, Difficulty: MEDIUM, UAT

#476 Bugfix bulk upload input improved error handling
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: Quality Control, bug

#457 Let programs with different types share the same course code
  cassdegrees/api/models.py
  cassdegrees/ui/forms.py
  cassdegrees/ui/views/staff/listings.py
Labels: Difficulty: EASY, UAT

#474 Check types correctly when in non-global-requirements areas
  cassdegrees/static/js/main.js
Labels: bug

#456 Truncate courses in course lists in PDFs to avoid filling up entire page
  cassdegrees/templates/pdf_base.html
  cassdegrees/templates/pdf_program.html
  cassdegrees/templates/widgets/pdf_rules.html
  cassdegrees/ui/templatetags/course_boxes.py
Labels: Difficulty: MEDIUM, UAT

#481 Fix deleting courses in lists from returning no error
  cassdegrees/templates/staff/creation/createlist.html
  cassdegrees/ui/views/staff/courses.py
Labels: bug

#485 Remove rules from Course Creation
  cassdegrees/static/js/main.js
  cassdegrees/templates/staff/creation/createcourse.html
  cassdegrees/ui/forms.py
Labels: Quality Control

#486 Wrote Function to Reformat the Column Names on listings.py
  cassdegrees/ui/views/staff/listings.py
Labels: Difficulty: EASY, User Story, Wishlist

#487 Made unpublished plans and subplans visible on the list page
  cassdegrees/static/css/style.css
  cassdegrees/templates/staff/list.html
  cassdegrees/ui/views/staff/listings.py
Labels: Difficulty: EASY, feature

#489 Make the list page sort date by default
  cassdegrees/static/js/staff/globalrequirements.js
  cassdegrees/templates/widgets/rules/course_elective.html
  cassdegrees/ui/views/staff/listings.py
Labels: Difficulty: EASY

#492 Improved processing of Excel files in custom format and Improved error handling
  cassdegrees/ui/views/staff/bulk_data_upload.py
Labels: Difficulty: MEDIUM, bug, feature
